Use assemble from https://github.com/sclorg/s2i-python-container/blob/master/2.7/s2i/bin/assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,11 +1,73 @@
-#!/bin/bash
+!/bin/bash
 
-set -eo pipefail
+function is_django_installed() {
+  python -c "import django" &>/dev/null
+}
 
-touch somefile && echo "Touched some other file"
+function should_collectstatic() {
+  is_django_installed && [[ -z "$DISABLE_COLLECTSTATIC" ]]
+}
 
-pip install --upgrade pip setuptools wheel
-pip install -r ${APP_HOME}/requirements.txt
-python ${APP_HOME}/manage.py collectstatic --noinput
+# Install pipenv to the separate virtualenv to isolate it
+# from system Python packages and packages in the main
+# virtualenv. Executable is simlinked into ~/.local/bin
+# to be accessible. This approach is inspired by pipsi
+# (pip script installer).
+function install_pipenv() {
+  echo "---> Installing pipenv packaging tool ..."
+  VENV_DIR=$HOME/.local/venvs/pipenv
+  virtualenv $VENV_DIR
+  $VENV_DIR/bin/pip --isolated install -U pipenv
+  mkdir -p $HOME/.local/bin
+  ln -s $VENV_DIR/bin/pipenv $HOME/.local/bin/pipenv
+}
 
-# /usr/libexec/s2i/assemble
+set -e
+
+shopt -s dotglob
+echo "---> Installing application source ..."
+mv /tmp/src/* ./
+
+if [[ ! -z "$UPGRADE_PIP_TO_LATEST" || ! -z "$ENABLE_PIPENV" ]]; then
+  echo "---> Upgrading pip to latest version ..."
+  pip install -U pip setuptools wheel
+fi
+
+if [[ ! -z "$ENABLE_PIPENV" ]]; then
+  install_pipenv
+  echo "---> Installing dependencies via pipenv ..."
+  if [[ -f Pipfile ]]; then
+    pipenv install --deploy
+  elif [[ -f requirements.txt ]]; then
+    pipenv install -r requirements.txt
+  fi
+  pipenv check
+elif [[ -f requirements.txt ]]; then
+  echo "---> Installing dependencies ..."
+  pip install -r requirements.txt
+elif [[ -f setup.py ]]; then
+  echo "---> Installing application ..."
+  python setup.py develop
+fi
+
+if should_collectstatic; then
+  (
+    echo "---> Collecting Django static files ..."
+
+
+    APP_HOME=${APP_HOME:-.}
+    # Look for 'manage.py' in the directory specified by APP_HOME, or the current directory
+    manage_file=$APP_HOME/manage.py
+
+    if [[ ! -f "$manage_file" ]]; then
+      echo "WARNING: seems that you're using Django, but we could not find a 'manage.py' file."
+      echo "'manage.py collectstatic' ignored."
+      exit
+    fi
+
+    python $manage_file collectstatic --noinput
+  )
+fi
+
+# set permissions for any installed artifacts
+fix-permissions /opt/app-root
